all:
	gcc -g -Wall -o balcao balcao.c
	gcc -g -Wall -o paciente paciente.c
	gcc -g -Wall -o medico medico.c

balcao:
	gcc -c balcao.c
paciente:
	gcc -c paciente.c
medico:
	gcc -c medico.c
clean:
	$(RM) balcao balcao.o
	$(RM) paciente paciente.o
	$(RM) medico medico.o
